var app = require('./server/server.js');

var http = require('http').Server(app);

var port = process.env.PORT || 3000;

var io = require('socket.io')(http);


http.listen(port, function() {
  console.log("listening to port ", port);
});

/////////
// socket.io logic
/////////

/*  allUsers holds the data for all logged-in users
{ 
  socketId: { username: JackSparrow, password: CoolHat}
}

note that the socketId is generated by socket.io and is unique for each client
*/
var allUsers = {};

// when a user connects
io.on('connection', function(socket) {

  // when a user disconnects
  socket.on('disconnect', function() {
    // send their user object to everyone
    io.emit('userExit', allUsers[socket.id])
  });

  // when a user sends their updated info
  socket.on('postUserUpdate', function(data) {

    // update the user data by accessing the allUsers object via the unique socket.id
    allUsers[socket.id] = data;

    // send the new user data to everyone
    io.emit('getUserUpdate', data);
  });

  // when the client asks for all of the user data
  socket.on('getAllUsers', function() {
    // send the entire user collection
    io.emit('allServerUsers', allUsers);
  });
});


module.exports = http;